manifest_version: 1

intention:
  - name: copy
    context: ['window', 'foo']
    run: 'foo'

layouts:
  linux_event_map:
    keymap:
      # special remap for my keytronic keyboard because F keys does not trigger on
      # my linux installation.
      - [['KEY_BRIGHTNESSDOWN'], ["@F1"]]
      - [['KEY_BRIGHTNESSUP'], ["@F2"]]
      - [['KEY_SCALE'], ["@F3"]]
      - [['KEY_DASHBOARD'], ["@F4"]]
      - [['KEY_KBDILLUMDOWN'], ["@F5"]]
      - [['KEY_KBDILLUMUP'], ["@F6"]]
      - [['KEY_PREVIOUSSONG'], ['@F7']]
      - [['KEY_PLAYPAUSE'], ['@F8']]
      - [['KEY_NEXTSONG'], ['@F9']]
      - [['KEY_MUTE'], ['@F9']]
      - [['KEY_VOLUMEDOWN'], ['@F11']]
      - [['KEY_VOLUMEUP'], ['@F12']]

      - [['KEY_F1'], ["@F1"]]
      - [['KEY_F2'], ["@F2"]]
      - [['KEY_F3'], ["@F3"]]
      - [['KEY_F4'], ["@F4"]]
      - [['KEY_F5'], ["@F5"]]
      - [['KEY_F6'], ["@F6"]]
      - [['KEY_F7'], ['@F7']]
      - [['KEY_F8'], ['@F8']]
      - [['KEY_F9'], ['@F9']]
      - [['KEY_F9'], ['@F9']]
      - [['KEY_F11'], ['@F11']]
      - [['KEY_F12'], ['@F12']]
      - [['KEY_INSERT'], ['@F13']]
      - [['KEY_SYSRQ'], ['@F13']]
      - [['KEY_DELETE'], ['@F14']]

      - [['KEY_GRAVE'], ["@M0"]]
      - [['KEY_1'], ["@M1"]]
      - [['KEY_2'], ["@M2"]]
      - [['KEY_3'], ["@M3"]]
      - [['KEY_4'], ["@M4"]]
      - [['KEY_5'], ["@M5"]]
      - [['KEY_6'], ["@M6"]]
      - [['KEY_7'], ["@M7"]]
      - [['KEY_8'], ["@M8"]]
      - [['KEY_9'], ["@M9"]]
      - [['KEY_0'], ["@M10"]]

      # Left set
      - [['KEY_Q'], ["@L11"]]
      - [['KEY_W'], ["@L12"]]
      - [['KEY_E'], ["@L13"]]
      - [['KEY_R'], ["@L14"]]
      - [['KEY_T'], ["@L15"]]

      - [['KEY_A'], ["@L21"]]
      - [['KEY_S'], ["@L22"]]
      - [['KEY_D'], ["@L23"]]
      - [['KEY_F'], ["@L24"]]
      - [['KEY_G'], ["@L25"]]

      - [['KEY_Z'], ["@L31"]]
      - [['KEY_X'], ["@L32"]]
      - [['KEY_C'], ["@L33"]]
      - [['KEY_V'], ["@L34"]]
      - [['KEY_B'], ["@L35"]]

      # Right set
      - [['KEY_Y'], ["@R11"]]
      - [['KEY_U'], ["@R12"]]
      - [['KEY_I'], ["@R13"]]
      - [['KEY_O'], ["@R14"]]
      - [['KEY_P'], ["@R15"]]

      - [['KEY_H'], ["@R21"]]
      - [['KEY_J'], ["@R22"]]
      - [['KEY_K'], ["@R23"]]
      - [['KEY_L'], ["@R24"]]
      - [['KEY_SEMICOLON'], ["@R25"]]

      - [['KEY_N'], ["@R31"]]
      - [['KEY_M'], ["@R32"]]
      - [['KEY_COMMA'], ["@R33"]]
      - [['KEY_DOT'], ["@R34"]]
      - [['KEY_SLASH'], ["@R35"]]

      # X set
      - [['KEY_TAB'], ["@X1"]]

      - [['KEY_CAPSLOCK'], ["@X2"]]

      - [['KEY_LEFTSHIFT'], ["@X31"]]
      - [['KEY_102ND'], ["@X32"]]

      - [['KEY_LEFTCTRL'], ["@X32"]]
      - [['KEY_LEFTMETA'], ["@X32"]]
      - [['KEY_LEFTALT'], ["@X32"]]

      # Space Set
      - [['KEY_SPACE'], ["@S"]]

      # Y Set
      - [['KEY_RIGHTALT'], ["@Y1"]]
      - [['KEY_COMPOSE'], ["@Y2"]]
      - [['KEY_RIGHTCTRL'], ["@Y3"]]

      # Y Set
      - [['KEY_UP'], ["@NU"]]
      - [['KEY_LEFT'], ["@NL"]]
      - [['KEY_DOWN'], ["@ND"]]
      - [['KEY_RIGHT'], ["@NR"]]

      # O Set
      - [['KEY_MINUS'], ["@O01"]]
      - [['KEY_EQUAL'], ["@O02"]]
      - [['KEY_BACKSPACE'], ["@O03"]]
      - [['KEY_PAGEUP'], ["@O04"]]

      - [['KEY_LEFTBRACE'], ["@O11"]]
      - [['KEY_RIGHTBRACE'], ["@O12"]]
      - [['KEY_BACKSLASH'], ["@O13"]]
      - [['KEY_PAGEDOWN'], ["@O14"]]

      - [['KEY_APOSTROPHE'], ["@O21"]]
      - [['KEY_ENTER'], ["@O22"]]
      - [['KEY_HOME'], ["@O24"]]

      - [['KEY_RIGHTSHIFT'], ["@O31"]]
      - [['KEY_END'], ["@O34"]]

  main:
    compile:
      - linux_event_map
      - fkeys
      - to_organize

    keymap:
      # - [["@M1"], ["doubleswitch:edit_mode"]]

      - [["@M0"], ["KEY_LEFTCTRL"]]
      - [['@M1'], ["#edit_mode"]]
      # - [['@M1'], ["#numpad", "#edit_mode"]]
      - [["@M2"], ["KEY_LEFTSHIFT"]]
      # - [['@M3'], ["#navigation_and_general_mode_right"]]
      - - - '@M4'
        - - "#keyboard_language_layout"

      - [['@M6'], ["#app"]]
      - [['@M8'], ["KEY_RIGHTSHIFT"]]
      - [['@M9'], ["KEY_LEFTCTRL"]]
      - [['@M10'], ["#navigation_and_general_left"]]
      - [['@O01'], ["#numpad_left"]]

      - [['@O11'], ["#char_1"]]
      - [['@O21'], ["#accents"]]

      - [["@M1", "@R31"], [">xdotool key Tab"]]

      - [["@X1"], ["KEY_LEFTMETA"]]

      - [["@X2", "@R21"], ["togglePowermode[]"]]
      - [["@X2", "@R25"], ["KEY_CAPSLOCK"]]

      - [["@O21"], ["KEY_RIGHTSHIFT"]]

      - [['@O11'], ["#additional_keys"]]

      # - [["@M10"], [">xdotool key U100"]]
  to_organize:
    keymap: []
      # - [['KEY_SHIFT', '@L11'], [">xdotool key U27"]] # "
      # - [['@L11'], [">xdotool key U27"]] # '
# "''""''""
  fkeys:
    keymap:
      - [["@F1"], ['KEY_F1']]
      - [["@F2"], ['KEY_F2']]
      - [["@F3"], ['KEY_F3']]
      - [["@F4"], ['KEY_F4']]
      - [["@F5"], ['KEY_F5']]
      - [["@F6"], ['KEY_F6']]
      - [['@F7'], ['KEY_F7']]
      - [['@F8'], ['KEY_F8']]
      - [['@F9'], ['KEY_F9']]
      - [['@F9'], ['KEY_F9']]
      - [['@F11'], ['KEY_F11']]
      - [['@F12'], ['KEY_F12']]
      - [['@F13'], ['KEY_INSERT']]
      - [['@F14'], ['KEY_DELETE']]

  # Find a better placement for thoses keys.
  additional_keys:
    keymap:
      - [["@L22"], ['KEY_APOSTROPHE']]
      - [["@L21"], ['KEY_LEFTBRACE']]

  # quotes:
  #   keymap:
  #     - [["@R21"], [">xdotool key asciitilde"]]
  #     - [["@r31"], [">xdotool key quoteright"]]
  #     - [["@M1", "KEY_SLASH"], [">xdotool key quotedbl"]]

  edit_mode:
    keymap:
      - [["@L13"], [">xdotool key --delay 0 ctrl+c"]]
      - [["@L14"], [">xdotool key --delay 0 ctrl+v"]]
      - [["@L15"], [">xdotool key --delay 0 BackSpace"]]

      - [["@L22"], [">xdotool key --delay 0 ctrl+s"]]
      - [["@L23"], [">xdotool key --delay 0 ctrl+z"]]
      - [["@L24"], [">xdotool key --delay 0 ctrl+y"]]
      - [["@L25"], [">xdotool key --delay 0 ctrl+g"]]

  char_1:
    keymap:
      - [["@L11"], [">xdotool key U3f"]] # ?
      - [["@L12"], [">xdotool key U60"]] # `
      - [["@L13"], [">xdotool key U2b"]] # +
      - [["@L14"], [">xdotool key U2d"]] # -
      - [["@L15"], [">xdotool key U3d"]] # =

      - [["@L21"], [">xdotool key U5c"]] # \
      - [["@L22"], [">xdotool key U2f"]] # /
      - [["@L23"], [">xdotool key U28"]] # (
      - [["@L24"], [">xdotool key U29"]] # )
      - [["@L25"], [">xdotool key U7c"]] # |

      - [["@L31"], [">xdotool key U5b"]] # [
      - [["@L32"], [">xdotool key U5d"]] # ]
      - [["@L33"], [">xdotool key U7b"]] # {
      - [["@L34"], [">xdotool key U7d"]] # }
      - [["@L35"], [">xdotool key U5f"]] # _
  accents:
    keymap:
      - [["@L11"], [">xdotool key Uf9"]] # ù
      - [["@L12"], [">xdotool key Ufb"]] # û
      - [["@L13"], [">xdotool key Ufc"]] # ü
      - [["@L14"], [">xdotool key Ue0"]] # à
      - [["@L15"], [">xdotool key Ue2"]] # â

      - [["@L21"], [">xdotool key Ue9"]] # é
      - [["@L22"], [">xdotool key Ue8"]] # è
      - [["@L23"], [">xdotool key Uea"]] # ê
      - [["@L24"], [">xdotool key Ueb"]] # ë
      - [["@L25"], [">xdotool key U20ac"]] # €

      - [["@L31"], [">xdotool key Ue6"]] # æ
      - [["@L32"], [">xdotool key U153"]] # œ
      - [["@L33"], [">xdotool key Ue7"]] # ç
      - [["@L34"], [">xdotool key Uf4"]] # ô
      - [["@L35"], [">xdotool key U7e"]] # ÿ
  accents_2:
    keymap:
      - [["@L11"], [">xdotool key Uef"]] # ï
      - [["@L12"], [">xdotool key Uee"]] # î
      - [["@L13"], [">xdotool key Uff"]] # ÿ

  navigation_and_general_mode_right:
    keymap:
      - [["@R13"], ["KEY_PAGEDOWN"]]
      - [["@R14"], ["KEY_PAGEUP"]]
      - [["@R12"], ["KEY_HOME"]]
      - [["@R15"], ["KEY_END"]]

      - [["@R24"], ["KEY_UP"]]
      - [["@R23"], ["KEY_DOWN"]]
      - [["@R22"], ["KEY_LEFT"]]
      - [["@R25"], ["KEY_RIGHT"]]

      - [["@R31"], ["KEY_ESC"]]
      - [["@R32"], ["KEY_BACKSPACE"]]
      - [["@R33"], ["KEY_ENTER"]]
      - [["@R34"], ["KEY_DELETE"]]

      - [['@R34'], ["KEY_MINUS"]]
      - [['@R35'], ["KEY_EQUAL"]]
  navigation_and_general_left:
    keymap:
      - [["@L11"], ["KEY_HOME"]]
      - [["@L13"], ["KEY_PAGEUP"]]
      - [["@L12"], ["KEY_PAGEDOWN"]]
      - [["@L14"], ["KEY_END"]]

      - [["@L21"], ["KEY_LEFT"]]
      - [["@L22"], ["KEY_DOWN"]]
      - [["@L23"], ["KEY_UP"]]
      - [["@L24"], ["KEY_RIGHT"]]
      - [["@L25"], ["KEY_TAB"]]

      - [["@L31"], ["KEY_ESC"]]
      - [["@L32"], ["KEY_BACKSPACE"]]
      - [["@L33"], ["KEY_ENTER"]]
      - [["@L34"], ["KEY_DELETE"]]

      # - [['@L34'], ["KEY_MINUS"]]
      # - [['@L35'], ["KEY_EQUAL"]]

  numpad:
    keymap:
      - [["@R32"], ["KEY_1"]]
      - [["@R33"], ["KEY_2"]]
      - [["@R34"], ["KEY_3"]]
      - [["@R22"], ["KEY_4"]]
      - [["@R23"], ["KEY_5"]]
      - [["@R24"], ["KEY_6"]]
      - [["@R12"], ["KEY_7"]]
      - [["@R13"], ["KEY_8"]]
      - [["@R14"], ["KEY_9"]]
      - [["@R25"], ["KEY_0"]]
  numpad_left:
    keymap:
      - [["@L31"], ["KEY_1"]]
      - [["@L32"], ["KEY_2"]]
      - [["@L33"], ["KEY_3"]]

      - [["@L21"], ["KEY_4"]]
      - [["@L22"], ["KEY_5"]]
      - [["@L23"], ["KEY_6"]]

      - [["@L11"], ["KEY_7"]]
      - [["@L12"], ["KEY_8"]]
      - [["@L13"], ["KEY_9"]]

      - [["@L24"], ["KEY_0"]]

  app:
    keymap:
      - [["@L11"], [">google-chrome"]] #
      - [["@L12"], [">firefox"]] #
      - [["@L13"], [">code -n --disable-gpu /home/goaman"]] #
      - [["@l15"], [">spotify"]] #

      - [["@l21"], [">obs"]] #
      - [["@L22"], [">inkscape"]] #
      - [["@L23"], [">blender"]] #

      - [["@L31"], [">discord"]] #

  app_util:
    keymap:
      - [["KEY_SYSRQ"], ['>gnome-screenshot -f ~/captures/$(date +%s).png']]

      - [["@O11"], [">gpick -p"]]
      - [["@O12"], [">flameshot gui -p /home/goaman/captures"]]

      - [["@R11"], [">slock"]] #
      - [["@R15"], [">xkill"]] #


      # need to be with a left modifier
      - [["@L T"], [">/usr/bin/copyq toggle"]] #

  screen:
    keymap:
      - [['@R32'], [">/home/goaman/goamanc/bin/xrandoff"]]
      - [['@R33'], [">/home/goaman/goamanc/bin/xrandon"]]
      - [['@R34'], [">/home/goaman/goamanc/bin/xrand_screen2"]]

  keyboard_language_layout:
    keymap:
      # - [["@R32"], ['>setxkbmap us dvorak-intl']]
      - [["@R32"], ['>setxkbmap us dvorak']]
      - [["@R33"], ['>setxkbmap us']]
      - [["@R34"], ['>setxkbmap be']]

  mouse:
    # scroll
    # click
    # move mouse
    # - quick
    # - midlle
    # - slow

  razer_mouse:
    keymap:
      - [["KEY_F1"], ['KEY_LEFTCTRL']]
      - [["KEY_F2"], ['KEY_RIGHTSHIFT']]
      - [["KEY_F3"], ['#navigation_and_general_left']]
      - [["KEY_F4"], ['#accents']]
      - [["KEY_F5"], ['#numpad_left']]
      - [["KEY_F6"], ['#char_1']]

      - [['KEY_F7'], ["#additional_keys"]]
      # - [["KEY_F8"], ['']]
      # - [["KEY_F9"], ['']]
      # - [["KEY_F10"], ['']]
      # - [["KEY_F11"], ['']]
      - [["KEY_F12"], ['BTN_RIGHT']]

      # - [["KEY_F13"], ['']]
      # - [["KEY_F14"], ['#left_as_right']]
      - [["KEY_F15"], ['#left_as_right']]
  left_as_right:
    keymap:
      - [["@L11"], ['KEY_Y']]
      - [["@L12"], ['KEY_U']]
      - [["@L13"], ['KEY_I']]
      - [["@L14"], ['KEY_O']]
      - [["@L15"], ['KEY_P']]

      - [["@L21"], ['KEY_H']]
      - [["@L22"], ['KEY_J']]
      - [["@L23"], ['KEY_K']]
      - [["@L24"], ['KEY_L']]
      - [["@L25"], ['KEY_SEMICOLON']]

      - [["@L31"], ['KEY_N']]
      - [["@L32"], ['KEY_M']]
      - [["@L33"], ['KEY_COMMA']]
      - [["@L34"], ['KEY_DOT']]
      - [["@L35"], ['KEY_SLASH']]

  empty:
    keymap: []
keyboards:
  - name: none
    layout: main

  - name: Keychron Keychron K2
    layout: main

  - name: Razer Razer Naga Pro
    layout: razer_mouse
    include:
      phys: /input2

  - name: Razer Naga Pro
    layout: razer_mouse
    include:
      phys: /input2

  - name: Naga Pro Keyboard
    layout: razer_mouse

  # - name: Razer Razer Naga Pro
  #   layout: empty


  # - name: Razer Naga Pro Keyboard
  #   layout: razer_mouse

  # - name: Razer Razer Blade Keyboard
  #   layout: main

